noise:
  # X, Y, Z
  positionNoise: [0.01, 0.01, 0.1]  # steering angle uses z

  # Yaw, Pitch, Roll
  orientationNoise: [0.001, 0.0, 0.001]  # EKF euler angle uses roll

  # X, Y, Z
  linearVelocityNoise: [0.1, 0.1, 0.0]  # imu velocity uses

  # X, Y, Z
  angularVelocityNoise: [0.0, 0.0, 0.1]  # imu velocity uses

  # X, Y, Z
  linearAccelerationNoise: [0.0, 0.0, 0.0]

  # lf, rf, lb, rb
  wheelSpeedNoise: [0.5, 0.5, 0.3, 0.3]  # wheel odom uses
